---
# XLSCHEMA Configuration
# ================================================================

# GLOBAL SETTINGS
# ----------------------------------------------------------------
settings:
    global:
        options:
            # output: ./tests/data/output
            # prefix: test
            clean: false

    # PLUGIN SETTINGS
    # ------------------------------------------------------------
    plugins:

        from_uri:
            active: true
            options:
                # format:
                run: false
                populate: false
                update_only: false
                models_only: false
                tables: []
                sql: []
                view:

        echo:
            active: true
            options:
                hello: world

        display:
            active: true
            options:
                offset: 20
                qualify: false

        to_sqla:
            active: true
            options:
                # prefix: test
                uri: sqlite:///tests/data/db/test.sqlite
                view: false

        split_xlsx:
            active: true
            options:
                keep_sheet: []
                group_on:
                sheet:

# LOGS
# ----------------------------------------------------------------
logging:
    version: 1
    disable_existing_loggers: false

    formatters:
        colored:
            class: colorlog.ColoredFormatter
            # format: '%(log_color)s[%(asctime)s] [%(levelname)-8s] --- %(message)s'
            # format: '%(log_color)s%(levelname)-8s%(reset)s%(asctime)s %(bold_yellow)s%(module)s:%(lineno)d%(reset)s %(message)s'
            # format: '%(log_color)s%(levelname)-8s%(reset)s%(asctime)s %(bold_cyan)s%(name)-24s%(reset)s %(message)s'
            format: '%(log_color)s%(levelname)-8s%(reset)s %(bold_cyan)s%(name)-24s%(reset)s %(message)s'
            datefmt: '%H:%M:%S'
            reset: true
            log_colors:
                DEBUG: cyan
                INFO: green
                WARNING: yellow
                ERROR: red
                CRITICAL: red
        standard:
            format: '%(asctime)s [%(levelname)-8s] %(name)s.%(funcName)s: %(message)s'
            datefmt: '%H:%M:%S'
        short:
            format: '%(asctime)s [%(levelname)-8s] %(name)s: %(message)s'
            datefmt: '%H:%M:%S'
        info:
            format: '[%(asctime)s] [%(levelname)-8s] --- %(message)s'
            datefmt: '%H:%M:%S'
        basic:
            format: '%(asctime)s [%(levelname)-8s] %(name)s: %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
        extended:
            # format: '%(asctime)s [%(levelname)-8s] %(name)24s.%(funcName)-12s: %(message)s'
            format: '%(asctime)s [%(levelname)-8s] %(name)-26s: %(message)s'
            datefmt: '%H:%M:%S'

    handlers:
        console:
            level: DEBUG
            # formatter: short
            formatter: colored
            class: logging.StreamHandler
            stream: ext://sys.stdout

        default:
            level: INFO
            formatter: standard
            class: logging.StreamHandler

        # debug_file_handler:
        #     class: logging.handlers.RotatingFileHandler
        #     level: DEBUG
        #     formatter: standard
        #     filename: ./tests/data/logs/info.log
        #     maxBytes: 10485760  # 10MB
        #     backupCount: 20
        #     encoding: utf8

        # error_file_handler:
        #     class: logging.handlers.RotatingFileHandler
        #     level: ERROR
        #     formatter: standard
        #     filename: ./tests/data/logs/errors.log
        #     maxBytes: 10485760  # 10MB
        #     backupCount: 20
        #     encoding: utf8

    loggers:
        plugins:
            level: WARN
            handlers: [console]
            propagate: false

    root:
        level: INFO
        # level: DEBUG
        handlers: [console]
        # handlers: [console, debug_file_handler, error_file_handler]
        propogate: false
